# Generated by Django 4.1.5 on 2023-01-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_team_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamcommitteemember',
            name='user',
        ),
    ]
