# Generated by Django 4.1.5 on 2023-01-13 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_teamcommitteemember_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='price',
            new_name='basePrice',
        ),
        migrations.AddField(
            model_name='player',
            name='soldPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TeamAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('dueCoins', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCategoryForAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('players', models.ManyToManyField(related_name='Player_Category', to='mainapp.player')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.tournament')),
            ],
        ),
    ]
